blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://discord.gg/MuPU7cs9rr
    about: "If you have a simple question, consider using the #support channel in our Discord server instead of opening an issue."
